[package]
name = "rstart"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[target.'cfg(windows)'.dependencies]
winapi = "*"
advapi32-sys = "*"
kernel32-sys = "*"
shell32-sys = "*"
